---
Resources:
  # IoT policy for cognito users
  UserIoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      # PolicyName: ${self:custom.cloudcam.userIoTPolicyName}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # connect from websocket client
          - Effect: Allow
            Action:
              - iot:Connect
            Resource: "arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}:client/wss-client-*"
          # read/update shadow for thing
          - Effect: Allow
            Action:
              - iot:GetThingShadow
              - iot:UpdateThingShadow
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'thing/${iot:Connection.Thing.ThingName}'
          - Effect: Allow
            Action:
              - iot:Subscribe
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update/accepted'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/get/accepted'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/cloudcam/${iot:Connection.Thing.ThingName}/notifications'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/cloudcam/${iot:Connection.Thing.ThingName}/commands'
          - Effect: Allow
            Action:
              - iot:Receive
              - iot:Publish
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/update'

  CameraIoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      # PolicyName: ${self:custom.cloudcam.cameraIoTPolicyName}
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # connect from websocket client
          - Effect: Allow
            Action:
              - iot:Connect
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'client/${iot:ClientId}'
          - Effect: Allow
            Action:
              - iot:Receive
              - iot:Publish
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/*'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/cloudcam/${iot:Connection.Thing.ThingName}/commands'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/cloudcam/${iot:Connection.Thing.ThingName}/notifications'
          - Effect: Allow
            Action:
              - iot:Receive
              - iot:Subscribe
            Resource:
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/$aws/things/${iot:Connection.Thing.ThingName}/shadow/*'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/cloudcam/${iot:Connection.Thing.ThingName}/commands'
              - 'Fn::Join':
                - ':'
                -
                  - 'arn:aws:iot:#{AWS::Region}:#{AWS::AccountId}'
                  - 'topicfilter/cloudcam/${iot:Connection.Thing.ThingName}/notifications'
