---
Resources:
  ThumbStoreRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '#{AWS::StackName}-ThumbStoreRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:PutObject
                Effect: Allow
                Resource: !Sub 'arn:aws:s3:::#{ThumbBucket}/*'
              - Effect: Allow
                Action:
                  - iot:Publish
                  - iot:Connect
                  - iot:UpdateThingShadow
                Resource:
                  - '*'

  CognitoPresignupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '#{AWS::StackName}-CognitoPresignupLambdaRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iot:DescribeEndpoint
                Resource: '*'

  IoTAttachUserPolicyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '#{AWS::StackName}-IotAttachUserPolicyLambdaRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iot:AttachPolicy
                Resource: '*'

  IoTAttachCameraPolicyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '#{AWS::StackName}-IoTAttachCameraPolicyLambdaRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iot:DescribeEndpoint
                  - iot:AttachPolicy
                  - iot:UpdateThing
                Resource: '*'

  IoTProvisionThingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '#{AWS::StackName}-IotProvisionThingLambdaRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iot:DescribeEndpoint
                  - iot:CreatePolicy
                  - iot:DeletePolicy
                  - iot:AttachPrincipalPolicy
                  - iot:DetachPrincipalPolicy
                  - iot:CreateThing
                  - iot:CreateKeysAndCertificate
                  - iot:AttachThingPrincipal
                Resource: '*'

  IotListThingsLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub '#{AWS::StackName}-IotListThingsLambdaRole'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iot:ListPrincipalPolicies
                  - iot:DescribeThing
                Resource: '*'

Outputs:
  IdentityPoolId:
    Description: 'Id of the Cognito identity pool'
    Value: !Ref CognitoIdentityPool
  UserPoolId:
    Description: 'Cognito user pool id'
    Value: !Ref CognitoUserPool
  UserPoolName:
    Description: 'Name of the Cognito user pool'
    Value: !GetAtt [CognitoUserPool, ProviderName]
  UserPoolClientName:
    Description: 'Name of the Cognito user pool web client'
    Value: !Ref CognitoClient
  UiUrl:
    Description: 'URL of the UI'
    Value: !GetAtt [UiBucket, WebsiteURL]
  Region:
    Value: '#{AWS::Region}'
  StackName:
    Value: '#{AWS::StackName}'
